version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=participants
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb/mongo-entrypoint/:/docker-entrypoint-initdb.d/
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: always
